### ISSUE TITLE
Line 翻译问题

### ISSUE THREAD

**Issue by pluwen** [cute/SketchI18N#10]
Line 有两个地方用到，但是只能提供一个翻译

Line，在工具里面翻译为「直线」
Line，在文本的属性，应该翻译为「行高」

**Comment by cute** [comment]
已经修复了

**Comment by pluwen** [comment]
1.0.3 还是显示为「直线」，正常应该是「行高」
英文里面  Line Height 太长，作者省略了

**Comment by pluwen** [comment]
感谢，已生效
