### ISSUE TITLE
请问，如何能回到英文状态？现在我无论如何toggle，或者卸载插件，都是中文了

### ISSUE THREAD

**Issue by Tairraos** [cute/SketchI18N#121]
请问，如何能回到英文状态？现在我无论如何toggle，或者卸载插件，都是中文了。

**Comment by pluwen** [comment]
从 Sketch 54 版本开始，官方提供简体中文，所以你卸载插件，也还是中文

如果你需要显示英文，可以把系统改成英文，Sketch 就会显示为英文版
或者
在mac的终端里面运行以下命令
`defaults write com.bohemiancoding.sketch3 AppleLanguages '(en)'`
改为中文，则运行
`defaults write com.bohemiancoding.sketch3 AppleLanguages '(zh-CN)'`

**Comment by Tairraos** [comment]
> 从 Sketch 54 版本开始，官方提供简体中文，所以你卸载插件，也还是中文
> 
> 如果你需要显示英文，可以把系统改成英文，Sketch 就会显示为英文版
> 或者
> 在mac的终端里面运行以下命令
> `defaults write com.bohemiancoding.sketch3 AppleLanguages '(en)'`
> 改为中文，则运行
> `defaults write com.bohemiancoding.sketch3 AppleLanguages '(zh-CN)'`

很好用，收藏下来了。谢谢~ 
是不是因为toggle实际上是切换中文和os语言的，我的os语言是中文所以切不因英文的？
希望能把这个功能加到菜单项里。菜单项变成3项：中文，英文，自动（跟随os设置)

谢谢谢谢
