### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by Lewanny** [cute/SketchI18N#13]
下载附件 
双击文件中的砖石安装 
提示安装成功后点OK进入sketch 
...结果，sketch插件文件夹里显示“不可用”
为什么咧，，，

大神，求指教

**Comment by utom** [comment]
新建一个文件就可用了

**Comment by pluwen** [comment]
@Lewanny 
Sketch 更新到最新的版本，然后下载最新版的 I18N
再试试看
