### ISSUE TITLE
和Sketch Craft插件有冲突

### ISSUE THREAD

**Issue by lemonweb** [cute/SketchI18N#15]
![qq20160725-0 2x](https://cloud.githubusercontent.com/assets/20622127/17084856/80792204-51fb-11e6-986a-c7516fc3ea81.png)
启用SketchI18N后，Craft插件的一些按钮会出现问题。

默认样式：
![qq20160725-1 2x](https://cloud.githubusercontent.com/assets/20622127/17084863/be4c9d36-51fb-11e6-8210-8bcaf51f6627.png)

**Comment by cute** [comment]
已经修复了
