### ISSUE TITLE
Try running the Plugin automatically when Sketch is launched

### ISSUE THREAD

**Issue by bomberstudios** [cute/SketchI18N#18]
You say on the README:

> Each time you open an application will need to run the plug-in to change language

With the [new Action API](http://developer.sketchapp.com/blog/2016-05-12-plugin-news/) you can probably run the Plugin when Sketch is launched.

BTW, congratulations on the Plugin, it looks really awesome.

**Comment by pluwen** [comment]
@cute 是否可行

**Comment by cute** [comment]
@bomberstudios  Thank you for your suggestion
@pluwen 可行，我已经更新了，可以自动加载了。

**Comment by pluwen** [comment]
@cute 感动的一塌糊涂

**Comment by utom** [comment]
@bomberstudios Cool~
