### ISSUE TITLE
SketchI18N BUG

### ISSUE THREAD

**Issue by lemonweb** [cute/SketchI18N#21]
![Uploading QQ20160726-0@2x.png…]()
更新后“插入”菜单的子菜单无法正常弹出

**Comment by pluwen** [comment]
我这边很正常
Sketch更新到最新版
汉化插件也更新到最新版
再试试看

**Comment by lemonweb** [comment]
sketch3.91，插件也是卸载了再安装的，试了几次还是不行，不过不影响正常使用，只有插入这个菜单的子菜单不能弹出

**Comment by pluwen** [comment]
发现了，确实有这个问题
@cute 
在菜单栏的「插入」
