### ISSUE TITLE
在dock右键菜单，打开近期的文件，会闪退

### ISSUE THREAD

**Issue by pluwen** [cute/SketchI18N#27]
RT @cute

**Comment by cute** [comment]
我测试没有问题，你的文件名是什么？

**Comment by pluwen** [comment]
关闭窗口，但是不退出sketch
在右键菜单打开最近的文件
必定闪退。。。

**Comment by cute** [comment]
@pluwen 这个我重现不了。

**Comment by pluwen** [comment]
@cute 现在的情况是，在打开一个项目的情况下，新建项目，也会闪退

**Comment by cute** [comment]
@pluwen 我版本Version 39.1 (31720) 重现不了

**Comment by pluwen** [comment]
我也是一样的版本。。。持续重现。。。不能打开两个文档
