### ISSUE TITLE
已勾选的文本会变成蓝色

### ISSUE THREAD

**Issue by pluwen** [cute/SketchI18N#29]
英文版正常

**Comment by cute** [comment]
能否截图说明下

**Comment by pluwen** [comment]
![image](https://cloud.githubusercontent.com/assets/555720/17238248/ba0796ba-558c-11e6-9f84-7dabce420fe5.png)

**Comment by pluwen** [comment]
![image](https://cloud.githubusercontent.com/assets/555720/17238281/0ef342d2-558d-11e6-9da1-1eb79a8f0745.png)
