### ISSUE TITLE
部分词条翻译后不生效问题

### ISSUE THREAD

**Issue by pluwen** [cute/SketchI18N#40]
![image](https://cloud.githubusercontent.com/assets/555720/18267032/e9bd8630-744f-11e6-91d2-9a616caf3f37.png)
这两句话在词条里面已经翻译过，但是没有生效，不知道哪里出问题，麻烦 @cute  看下

![image](https://cloud.githubusercontent.com/assets/555720/18270257/979f35c4-745e-11e6-82c0-91375219f1ab.png)
这个也是

**Comment by cute** [comment]
@pluwen 你可以在自定义插件运行 `log(SketchI18NPluginManager.pendingStrings());`来查看缺失的文字。

**Comment by pluwen** [comment]
@cute 运行之后，发现里面的词条很少，没有包含图上面这些

**Comment by cute** [comment]
@pluwen 需要你在操作相关页面后，发现有未翻译的词语，然后通过运行 `log(SketchI18NPluginManager.pendingStrings());` 查看具体是什么词语。

**Comment by pluwen** [comment]
@cute 懂了，很方便
