### ISSUE TITLE
无法翻译，不确定因素

### ISSUE THREAD

**Issue by lemonweb** [cute/SketchI18N#47]
不知道是不是因为我升级了MacOS的原因，在sketch 39.1下，SketchI18N不能再汉化了。

**Comment by pluwen** [comment]
升级到 Sketch 40 试试看，另外，SketchI18N 也更新到最新

**Comment by lemonweb** [comment]
好吧，其实这样的，我升级到Sketch 40了，发现变为试用期，然后，I18N也不能翻译了，然后我把I18N升级到最新，还是不可以，我以为是Sketch 40不支持，又把软件全部删除，清空数据，重新安装Sketch 39.1，但依然无法汉化，好郁闷。。。。昨天还是汉化的。。。

**Comment by cute** [comment]
晚上我升级下macOS试试

**Comment by lemonweb** [comment]
你现在升级sketch40是可以正常汉化的？

**Comment by cute** [comment]
是的，我操作系统版本还是10.11.6

**Comment by utom** [comment]
目测应该是操作系统的问题~

**Comment by lemonweb** [comment]
已解决~😀
