### ISSUE TITLE
你好，没有找到邮箱地址，只能在这里问个有关shadowrocket的问题了，请见谅。

### ISSUE THREAD

**Issue by fun5rt** [cute/SketchI18N#50]
原来我都是用越狱的ios系统的，可以直接更改hosts文件。现在的ios10不能越狱，通过搜索我找到你开发的shadowrocket软件，想要起到加载hosts的作用。

我是这样设置的：
configuration里我是空的，因为我还没买ss
settings-global routing 我选的direect
settings-dns-hosts 里我复制了电脑版本的hosts

其他的都是默认，直接打开开关，iPhone状态栏显示vpn标志。
打开后感觉设置的hosts是起作用的，Google，Facebook都可以登录。

然而问题是，一旦长时间没有操作手机，自动锁屏之后，再解锁就不能联网了，使用浏览器任何网页都打不开（直接访问ip也不行），此时状态栏vpn标志依旧在的。需要我重新连接shadowrocket才可以。

这个问题该如何解决呢？

**Comment by cute** [comment]
等新版

**Comment by fun5rt** [comment]
大概需要等多久会有新版本的更新？

**Comment by cute** [comment]
在等审核。

**Comment by fun5rt** [comment]
今天更新了，原来只是通过widget开关会跳转app的，更新后widget那儿就不能控制开关呀？ios 10.0.2 iphone 7

**Comment by cute** [comment]
你自己试试不就知道了

**Comment by fun5rt** [comment]
我试了两个iPhone ，widget差价都不能控制开关，应该个别现象吧？
