### ISSUE TITLE
系统语言是英文，可以设置sketch是中文么？

### ISSUE THREAD

**Issue by snowjade** [cute/SketchI18N#96]
发现在系统语言是英文时 不能设置sketch中文，只有切到中文才行。但是我习惯英文系统，只有部分不熟的软件用中文的，有什么解决办法么？

**Comment by snowjade** [comment]
解决了，把获取系统语言来动态设置sketch语言，改为 写死成用中文就行了。

**Comment by LgdMagic** [comment]
怎么修改呢？具体怎么做？谢谢

**Comment by snowjade** [comment]
@LgdMagic 显示包内容，然后看看里面的代码， 找到相关的 改下就行了。  你好像做开发的吧，应该能行。
